name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  django-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install

    - name: Create .env
      run: |
        echo "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY" > .env
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    - name: Setup SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        known_hosts: unnecessary

    - name: Accept host fingerprint
      run: |
        ssh -o StrictHostKeyChecking=accept-new root@test.django-up.com "ls"

    - name: Run up
      run: |
        pipenv run python manage.py up test.django-up.com --email=brenton@brntn.me
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    - name: Remove .env
      run: rm .env
